# Generated by Django 5.0.3 on 2024-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('marks', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
