# Generated by Django 5.0.3 on 2024-03-28 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0002_alter_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onetoone.address'),
        ),
    ]
